### ISSUE TITLE
Error on calling super()

### ISSUE THREAD

**Issue by juliobetta** [pixelpicosean/slush-phaser-project#23]
I'm getting this error in the console when calling `super()`.

`Uncaught TypeError: $traceurRuntime.superCall is not a function`

This is one of my classes:

```
class Starfield extends Phaser.TileSprite {

  constructor(game) {
    super(game, 0, 0, 800, 600, 'starfield');

    this.autoScroll(0.0, 200.0);
  }

}

export default Starfield;
```

**Comment by pixelpicosean** [comment]
Looks like your traceur runtime is not installed successfully. Make sure bower is installed globally and there's no issue during project creating.

If you are new to use this, I recommend you to use [https://github.com/rblopes/my-phaser-template](https://github.com/rblopes/my-phaser-template) instead since this project is no longer maintained.

Good luck.
